version: "3.3"
services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_CLIENT_PORT: 2181
   
  kafka:
    hostname: kafka
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9021:9021
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092

  kafdrop:
    hostname: kafdrop
    container_name: kafdrop
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  elasticsearch:
    hostname: elasticsearch
    container_name: elasticsearch
    build:
      context: ./elasticsearch
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - kafka
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw

  logstash:
    hostname: logstash
    container_name: logstash
    build:
      context: ./logstash
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    network_mode: "host"

  kibana:
    hostname: kibana
    container_name: kibana
    build:
      context: ./kibana
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  elk2:
    build: .
    container_name: elk2
    depends_on:
      - zookeeper
      - kafka
    network_mode: "service:kafka"

volumes:
  esdata:
    driver: local